.class public interface abstract Ldagger/hilt/android/internal/managers/HiltWrapper_ActivityRetainedComponentManager_ActivityRetainedComponentBuilderEntryPoint;
.super Ljava/lang/Object;
.source "HiltWrapper_ActivityRetainedComponentManager_ActivityRetainedComponentBuilderEntryPoint.java"

# interfaces
.implements Ldagger/hilt/android/internal/managers/ActivityRetainedComponentManager$ActivityRetainedComponentBuilderEntryPoint;
