.class public final Lkotlinx/parcelize/Parceler$DefaultImpls;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lkotlinx/parcelize/Parceler;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "DefaultImpls"
.end annotation


# direct methods
.method public static newArray(Lkotlinx/parcelize/Parceler;I)[Ljava/lang/Object;
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlinx/parcelize/Parceler<",
            "TT;>;I)[TT;"
        }
    .end annotation

    const-string p1, "this"

    invoke-static {p0, p1}, Lri/o;->e(Ljava/lang/Object;Ljava/lang/String;)V

    .line 1
    new-instance p0, Lgi/h;

    const-string p1, "Generated by Android Extensions automatically"

    invoke-direct {p0, p1}, Lgi/h;-><init>(Ljava/lang/String;)V

    throw p0
.end method
